# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: userservice
    ports:
      - "3306:3306"
